HighPaw/HighPaw.Web/Areas/Admin/Controllers/EventsController.cs
namespace HighPaw.Web.Areas.Admin.Controllers
{
    using HighPaw.Services.Event;
    using HighPaw.Services.Event.Models;
    using Microsoft.AspNetCore.Mvc;

    public class EventsController : BaseController
    {
        private readonly IEventService events;

        public EventsController(IEventService events)
            => this.events = events;

        public IActionResult All()
        {
            var allArticles = this.events.All();

            return View(allArticles);
        }

        public IActionResult Edit(int? id)
        {
            if (id is null)
            {
                return NotFound();
            }

            var model = this.events
                .GetById(id);

            if (model is null)
            {
                return NotFound();
            }

            return View(model);
        }

        [HttpPost]
        public IActionResult Edit(EventServiceModel model)
        {
            if (!this.events.DoesExist(model.Id))
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            this.events.Edit(model);

            return RedirectToAction(nameof(All));
        }

        public IActionResult Delete(int id)
        {
            this.events.Delete(id);

            return RedirectToAction(nameof(All));
        }
    }
}

HighPaw/HighPaw.Web/Areas/Admin/Controllers/PetsController.cs
namespace HighPaw.Web.Areas.Admin.Controllers
{
    using HighPaw.Services.Pet;
    using HighPaw.Services.Pet.Models;
    using HighPaw.Services.Shelter;
    using Microsoft.AspNetCore.Mvc;

    public class PetsController : BaseController
    {
        private readonly IPetService pets;
        private readonly IShelterService shelters;

        public PetsController(
            IPetService pets,
            IShelterService shelters)
        {
            this.pets = pets;
            this.shelters = shelters;
        }

        public IActionResult All()
        {
            var allPets = this.pets
                .All();

            return View(allPets);
        }

        public IActionResult Edit(int? id)
        {
            if (id is null)
            {
                return NotFound();
            }

            var model = this.pets
                .GetById(id);

            if (model is null)
            {
                return NotFound();
            }

            model.Categories = this.pets.AllCategories();
            model.Shelters = this.shelters.GetAllNames();

            return View(model);
        }

        [HttpPost]
        public IActionResult Edit(EditPetServiceModel model)
        {
            if (!this.pets.DoesExist(model.Id))
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            this.pets.Edit(model);

            return RedirectToAction(nameof(All));
        }

        public IActionResult Delete(int id)
        {
            var isDeleteSuccessfull = this.pets.Delete(id);

            return View(isDeleteSuccessfull);
        }
    }
}

HighPaw/HighPaw.Web/Controllers/ArticlesController.cs
namespace HighPaw.Web.Controllers
{
    using HighPaw.Services.Article;
    using HighPaw.Web.Infrastructure.Extensions;
    using HighPaw.Web.Models.Articles;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using static Areas.Admin.AdminConstants;
    using static HighPaw.Services.GlobalConstants;

    public class ArticlesController : Controller
    {
        private readonly IArticleService articles;

        public ArticlesController(IArticleService articles)
            => this.articles = articles;

        public IActionResult All()
        {
            var allArticles = this.articles
                .All();

            return View(allArticles);
        }

        public IActionResult Read(int id)
        {
            var article = this.articles.Read(id);

            return View(article);
        }

        [Authorize(Roles = $"{AdminRoleName},{VolunteerRoleName}")]
        public IActionResult Create()
        {
            string userFullName = User.FullName();

            return View(new ArticleFormModel
            {
                CreatorName = userFullName,
                ArticlesTypes = new[] { ArticleArticleType, StoryArticleType }
            });
        }

        [Authorize(Roles = $"{AdminRoleName},{VolunteerRoleName}")]
        [HttpPost]
        public IActionResult Create(ArticleFormModel article)
        {
            if (!ModelState.IsValid)
            {
                return View(article);
            }

            var articleId = this.articles
                .Create(
                article.Title,
                article.Content,
                article.ImageUrl,
                article.CreatorName,
                article.ArticleType);

            return RedirectToAction(nameof(All));
        }
    }
}

HighPaw/HighPaw.Web/Controllers/VolunteersController.cs
namespace HighPaw.Web.Controllers
{
    using HighPaw.Services.Volunteer;
    using HighPaw.Web.Infrastructure.Extensions;
    using HighPaw.Web.Models.Volunteers;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    public class VolunteersController : Controller
    {
        private readonly IVolunteerService volunteers;

        public VolunteersController(IVolunteerService volunteers)
            => this.volunteers = volunteers;


        [Authorize]
        public IActionResult Become()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public IActionResult Become(BecomeVolunteerFormModel model)
        {
            var userId = User.Id();

            var userIdAlreadyAVolunteer = this.volunteers
                .IsVolunteer(userId);

            if (userIdAlreadyAVolunteer)
            {
                return BadRequest();
            }

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            this.volunteers.Become(model.FirstName, model.LastName, model.Email, model.AllAboutYou, userId);

            ViewData["VolunteersMessage"] = "We will contact you with more details.";

            //TODO: Create a toast with VolunteersMessage

            return RedirectToAction("Index", "Home");
        }
    }
}

HighPaw/HighPaw.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title - HighPaw</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HighPaw.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">

</head>
<body>
    <div style="min-height: calc(100vh - 95px);">
        <header>
            <nav class="navbar navbar-expand-lg navbar-light fixed-top mask-custom shadow-0">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><span style="color: #5e9693;">High</span><span style="color: #fdc57b;">Paw</span></a>
                    <button class="navbar-toggler" type="button" data-mdb-toggle="collapse"
                            data-mdb-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                            aria-label="Toggle navigation">
                        <i class="fas fa-bars"></i>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        @if (!User.IsAdmin())
                        {
                            <ul class="navbar-nav me-auto">
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="Home" asp-action="HowToAdopt">How to adopt</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="Pets" asp-action="AllLost">Lost pets</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="Pets" asp-action="AllFound">Found pets</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="Articles" asp-action="All">Articles</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="Events" asp-action="All">Events</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="Home" asp-action="About">About</a>
                                </li>
                            </ul>
                        }
                        <partial name="_LoginPartial" />
                    </div>
                </div>
            </nav>
        </header>

        <div class="container app">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
    </div>
    <footer class="bg text-center text-lg-start text-white position-sticky" style="background-color: #fdc57b;">
        <div class="container pt-5 border-bottom">
            <div class="row my-4">
                <div class="col-lg-3 col-md-6 mb-4 mb-md-0 mx-4">

                    <div class="rounded-circle bg-white shadow-1-strong d-flex align-items-center justify-content-center mb-4 mx-auto" style="width: 150px; height: 150px;">
                        <img src="https://mdbootstrap.com/img/Photos/new-templates/animal-shelter/logo.png" height="70" alt=""
                             loading="lazy" />
                    </div>

                    <p class="text-center">Our goal is to keep pets out of the shelters</p>

                </div>
                <div class="col-lg-3 col-md-6 mb-4 mb-md-0  mx-2">
                    <h5 class="text-uppercase mb-4">Animals</h5>

                    <ul class="list-unstyled">
                        <li class="mb-2">
                            <a asp-controller="Pets" asp-action="Add" class="text-white"><i class="fas fa-paw pe-3"></i>When your pet is missing</a>
                        </li>
                        <li class="mb-2">
                            <a asp-controller="Pets" asp-action="AllFound" class="text-white"><i class="fas fa-paw pe-3"></i>Recently found</a>
                        </li>
                        <li class="mb-2">
                            <a asp-controller="Home" asp-action="HowToAdopt" class="text-white"><i class="fas fa-paw pe-3"></i>How to adopt?</a>
                        </li>
                        <li class="mb-2">
                            <a asp-controller="Pets" asp-action="AllFound" class="text-white"><i class="fas fa-paw pe-3"></i>Pets for adoption</a>
                        </li>
                        <li class="mb-2">
                            <a asp-controller="Volunteers" asp-action="Become" class="text-white"><i class="fas fa-paw pe-3"></i>Be Our Hero</a>
                        </li>
                        <li class="mb-2">
                            <a asp-controller="Home" asp-action="About" class="text-white"><i class="fas fa-paw pe-3"></i>Who we are</a>
                        </li>
                    </ul>
                </div>
                <div class="col-lg-3 col-md-6 mb-4 mb-md-0  mx-2">
                    <h5 class="text-uppercase mb-4">Contact</h5>

                    <ul class="list-unstyled">
                        <li>
                            <p><i class="fas fa-map-marker-alt pe-2"></i>Sofia, 57 Street, Bulgaria</p>
                        </li>
                        <li>
                            <p><i class="fas fa-phone pe-2"></i>+359 2 234 567 89</p>
                        </li>
                        <li>
                            <p><i class="fas fa-envelope pe-2 mb-0"></i>contact@HighPaw.com</p>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
            ©  @DateTime.UtcNow.Year - High Paw
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://kit.fontawesome.com/de5e749819.js" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

HighPaw/HighPaw.Web/Views/Shared/_SearchingPetsPartial.cshtml
@model AllPetsQueryModel

<div class="container" style="margin-top: 5rem;">
    <form method="get">
        <div class="input-group mb-3">
    <input asp-for="SearchString" type="text" class="form-control" placeholder="Search by breed, age, gender ect...">
    <button class="input-group-text shadow-none px-4 btn-warning">
        <i class="fa-solid fa-magnifying-glass"></i>
    </button>
</div>
</form>

<div class="d-grid gap-2 d-md-block">
    <a type="button" class="btn btn-outline-warning btn-rounded ml-2" data-mdb-ripple-color="dark" asp-controller="Pets" asp-action="Add">I Found A Pet</a>
    <a type="button" class="btn btn-outline-warning btn-rounded ml-2" data-mdb-ripple-color="dark" asp-controller="Pets" asp-action="Add">I Lost My Pet</a>
    </div>
</div>